### ISSUE TITLE
multiple selection

### ISSUE THREAD

**Issue by ybrs** [Hipo/hst#9]
nice work #8  

there are a few issues with https://github.com/Hipo/hst/pull/8 

i) I keep receiving this - not super sure about how this happens, but usually happens  when i multi select something, then write more - in query - and then select other and add some more etc query etc. i think happens when query doesnt have anything to show from history.

```
$ hst
Traceback (most recent call last):
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 521, in <module>
    main()
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 480, in main
    picker.key_pressed(char)
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 368, in key_pressed
    self.keys[char]()
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 304, in key_BACKSPACE
    self.refresh_window()
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 228, in refresh_window
    self.print_line("Results [%s]" % self.index.size(), highlight=True)
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 154, in print_line
    self.win.addstr(self.lineno, 0, line, curses.color_pair(1))
_curses.error: addstr() returned ERR
```

ii)  in multiple selection, when i am on a not selected line, i hit enter and i am asked, "want to include .... y/n" i hit y and get this. (this is pretty easy to reproduce)

```
$ hst -p
Traceback (most recent call last):
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 521, in <module>
    main()
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 480, in main
    picker.key_pressed(char)
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 368, in key_pressed
    self.keys[char]()
  File "/Users/aybarsbadur/projects/hst/hst/hst.py", line 271, in key_ENTER
    if a in "yY":
TypeError: 'in <string>' requires string as left operand, not int
```

i think we shouldn't ask that question btw, because i was really confused when i first saw that. we can either include the last line or don't - my vote is not including it - but it will be more easier to use without a question.

thank you for your pull request.

**Comment by ybrs** [comment]
fixed by commits in #8
